server:
  port: 8308

spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.1.221:3306/frequency
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
  profiles:
    active: dev
