server:
  port: ${UOP_SERVER_PORT:8307}
  context-path: ${UOP_SERVER_CONTEXT_PATH:/}

spring:
  kafka:
    bootstrap-servers: 192.168.1.252:9092
    producer:
      batch-size: 4096
      retries: 0
      buffer-memory: 33554432
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT + 8
  datasource:
      username: ${wz.sql.user.name:root}
      password: ${wz.sql.user.pwd:123456}
#     联调用test，之前用的unit
      url: jdbc:mysql://${TXL.jdbc.host:192.168.1.221}:${TXL.jdbc.port:3306}/${TXL.jdbc.database:wz}
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
  profiles:
    active: fan
#eureka:
#  client:
#    enabled: false



